model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "auto"
show_raw_agent_reasoning = true

suppress_unstable_features_warning = true

approval_policy = "never"
sandbox_mode = "danger-full-access"

project_doc_fallback_filenames = [
  "CLAUDE.md",
  "OS.AGENTS.md",
]
personality = "pragmatic"

web_search = "live"

[features]
multi_agent = true
responses_websockets_v2 = true
sqlite = true
memory_tool = true
undo = true

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[projects."/home/nb"]
trust_level = "trusted"

[agents]
max_threads = 12 # default is 6
# max_depth = 2 # waiting for the next release

[agents.explorer]
config_file = "./agents/explorer.toml"

# [mcp_servers.chrome-devtools]
# command = "npx"
# args = ["chrome-devtools-mcp@latest", "--autoConnect"]
